import axios, { AxiosError } from "axios";

export const API_BASE_URL = `http://192.168.0.101:5000`;

export const $api = axios.create({
  baseURL: API_BASE_URL,
  withCredentials: true,
});

export function isAxiosError(error: Error): error is AxiosError {
  return (error as AxiosError).isAxiosError;
}

export class RequestError extends Error {
  constructor(public innerException: any) {
    super("Во время запроса произошла ошибка");
    if (isAxiosError(innerException)) {
      if ((innerException as AxiosError).response?.status === 500) {
        // eslint-disable-next-line no-console
        console.error({
          content: "Ошибка сервера. Не удалось выполнить действие",
          duration: 3,
        });
      }
    }
  }
}
